trigger:
- main

pool: Agent ka pool

stages:

- stage: inittoplan
  jobs:
  - job: terraformjob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'nimacervice'
        backendAzureRmStorageAccountName: 'storageterra123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfvars'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'nimacervice'


- stage: mannualvalidation
  dependsOn: inittoplan

  jobs:
  - job: approval
    pool: server

    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'nimakumaripiet@gmail.com'
        instructions: 'Approve Terraform deployment'
        onTimeout: 'reject'

- stage: terraformapply
  jobs:
    - job: inittoapply
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'nimacervice'
          backendAzureRmStorageAccountName: 'storageterra123'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfvars'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'custom'
          outputTo: 'console'
          customCommand: 'apply -auto-approve'
          environmentServiceNameAzureRM: 'nimacervice'