trigger:
  - main

pool:
  name: "Agent ka pool"

stages:

  - stage: inittoplan
    displayName: "Terraform Init and Plan"

    jobs:
      - job: terraformjob
        displayName: "Terraform Init & Plan"

        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "nimacervice"
              backendAzureRmStorageAccountName: "stogeterra123"
              backendAzureRmContainerName: "tfstate"
              backendAzureRmKey: "terraform.tfvars"

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: "azurerm"
              command: "plan"
              environmentServiceNameAzureRM: "nimacervice"

  - stage: scanning
    displayName: "Scanning"

    jobs:
      - job: tfsecscan
        displayName: "Run tfsec Scan"

        pool:
          name: "Agent ka pool"

        steps:
          - script: |
              brew install tfsec
              tfsec .
            displayName: "Run tfsec Scan"

  - stage: manualvalidation
    displayName: "Manual Validation"
    dependsOn: inittoplan

    jobs:
      - job: approval
        displayName: "Approval Required"

        pool: server

        steps:
          - task: ManualValidation@1
            displayName: "Manual Approval"
            inputs:
              notifyUsers: "nimakumaripiet@gmail.com"
              instructions: "Approve Terraform deployment"
              onTimeout: "reject"

  - stage: terraformapply
    displayName: "Terraform Apply"
    dependsOn: manualvalidation

    jobs:
      - job: inittoapply
        displayName: "Terraform Apply Job"

        steps:
          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "nimacervice"
              backendAzureRmStorageAccountName: "stogeterra123"
              backendAzureRmContainerName: "tfstate"
              backendAzureRmKey: "terraform.tfvars"

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              commandOptions: "-auto-approve"
              environmentServiceNameAzureRM: "nimacervice"